git:
  depth: 3
  submodules: true

language: android

android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
    - sudo apt-get install libwebp5 webp python
    - echo `python --version`
    - export ANDROID_SDK_ROOT=/usr/local/android-sdk
    - wget https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip
    - unzip -qq android-ndk-r14b-linux-x86_64.zip -d $ANDROID_SDK_ROOT/ndk-bundle
    - export NDK_ROOT=$ANDROID_SDK_ROOT/ndk-bundle/android-ndk-r14b
    - echo -e "sdk.dir=$ANDROID_SDK_ROOT\nndk.dir=$NDK_ROOT\n" > local.properties
    - wget https://dl.google.com/firebase/sdk/cpp/firebase_cpp_sdk_3.1.0.zip
    - unzip -qq firebase_cpp_sdk_3.1.0.zip -d ./dependencies/
    - export FIREBASE_SDK=$(pwd)/dependencies/firebase_cpp_sdk/

script:
    - ./gradlew build
    - ./gradlew build
